# Generated by Django 6.0.3 on 2026-04-01 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='title',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='day',
        ),
        migrations.AddField(
            model_name='holiday',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='day_of_week',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], default='Mon', max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='department.department'),
        ),
    ]
