# Generated by Django 6.0.3 on 2026-03-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='city',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(max_length=200),
        ),
    ]
