# Generated by Django 6.0.3 on 2026-04-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_remove_teacher_city_remove_teacher_zip_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='address',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.AddField(
            model_name='teacher',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Ville'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='diploma',
            field=models.CharField(default='', max_length=200, verbose_name='Diplôme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='mobile_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='parcours',
            field=models.TextField(blank=True, null=True, verbose_name='Parcours Professionnel'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_photos/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.CharField(max_length=100),
        ),
    ]
