# Generated by Django 6.0.3 on 2026-04-01 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='departement',
            new_name='department',
        ),
    ]
