# Generated by Django 6.0.3 on 2026-03-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0003_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='z2y7P4e6TEtkQFPrEO6D6T7WbAHaaJDB', editable=False, max_length=32, unique=True),
        ),
    ]
