# Generated by Django 6.0.3 on 2026-03-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='9cMXpYF6gYGTlRNQ1QwxyKNWkw1hxY3Y', editable=False, max_length=32, unique=True),
        ),
    ]
