# Generated by Django 6.0.3 on 2026-03-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='iTtpUa9YrsPGYZiT7qa6hC57Fu1s8WQK', editable=False, max_length=32, unique=True),
        ),
    ]
