# Generated by Django 6.0.3 on 2026-03-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0007_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='1STT4e8Lb3NlB4E5bWceikPrthRbp59J', editable=False, max_length=32, unique=True),
        ),
    ]
