# Generated by Django 6.0.3 on 2026-04-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0011_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='79g3JbAEQLpoB1yC8A7hF5HzyVOv4Fb3', editable=False, max_length=32, unique=True),
        ),
    ]
