# Generated by Django 6.0.3 on 2026-04-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0017_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='hR2wnuIxINHXKMHacOaZ2EDousRsh07R', editable=False, max_length=32, unique=True),
        ),
    ]
