# Generated by Django 6.0.3 on 2026-04-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0019_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='dqPKxGuuq3NDbU7BoqrWeWuM41PlGrl9', editable=False, max_length=32, unique=True),
        ),
    ]
