# Generated by Django 6.0.3 on 2026-04-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0022_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Gi9lRl5hG5V4YO0Uvsf7JNKYvPzjItjq', editable=False, max_length=32, unique=True),
        ),
    ]
