# Generated by Django 6.0.3 on 2026-04-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0025_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='dCKILcKhWqYIxxztD0sD3RddhWW4ENb9', editable=False, max_length=32, unique=True),
        ),
    ]
